ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    # path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('', include('ads.urls')),  # Change to ads.urls
    # path('ads/', include('ads.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
           'show_indexes': True},
        name='site_path'
    ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using',social_login,'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

wizards/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name='wizards'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.WizardCreate.as_view(), name='wizard_create'),
    path('main/<int:pk>/update/', views.WizardUpdate.as_view(), name='wizard_update'),
    path('main/<int:pk>/delete/', views.WizardDelete.as_view(), name='wizard_delete'),
    path('lookup/', views.HouseView.as_view(), name='house_list'),
    path('lookup/create/', views.HouseCreate.as_view(), name='house_create'),
    path('lookup/<int:pk>/update/', views.HouseUpdate.as_view(), name='house_update'),
    path('lookup/<int:pk>/delete/', views.HouseDelete.as_view(), name='house_delete'),
]

wizards/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class House(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "House must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Wizard(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    power = models.PositiveIntegerField()
    spell = models.CharField(max_length=300)
    house = models.ForeignKey('House', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

wizards/forms.py
from django.forms import ModelForm
from wizards.models import House

# Create the form class.
class HouseForm(ModelForm):
    class Meta:
        model = House
        fields = '__all__'

wizards/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from wizards.models import Wizard, House
from wizards.forms import HouseForm

# Create your views here.

class MainView(LoginRequiredMixin, View) :
    def get(self, request):
        mc = House.objects.all().count();
        al = Wizard.objects.all();

        ctx = { 'make_count': mc, 'wizard_list': al };
        return render(request, 'wizards/wizard_list.html', ctx)

class HouseView(LoginRequiredMixin,View) :
    def get(self, request):
        ml = House.objects.all();
        ctx = { 'house_list': ml };
        return render(request, 'wizards/house_list.html', ctx)

# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class HouseCreate(LoginRequiredMixin, View):
    template = 'wizards/house_form.html'
    success_url = reverse_lazy('wizards:all')
    def get(self, request) :
        form = HouseForm()
        ctx = { 'form': form }
        return render(request, self.template, ctx)

    def post(self, request) :
        form = HouseForm(request.POST)
        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        house = form.save()
        return redirect(self.success_url)

# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class HouseUpdate(LoginRequiredMixin, View):
    model = House
    success_url = reverse_lazy('wizards:all')
    template = 'wizards/house_form.html'
    def get(self, request, pk) :
        house = get_object_or_404(self.model, pk=pk)
        form = HouseForm(instance=house)
        ctx = { 'form': form }
        return render(request, self.template, ctx)

    def post(self, request, pk) :
        house = get_object_or_404(self.model, pk=pk)
        form = HouseForm(request.POST, instance = house)
        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)

class HouseDelete(LoginRequiredMixin, View):
    model = House
    success_url = reverse_lazy('wizards:all')
    template = 'wizards/house_confirm_delete.html'

    def get(self, request, pk) :
        house = get_object_or_404(self.model, pk=pk)
        form = HouseForm(instance=house)
        ctx = { 'house': house }
        return render(request, self.template, ctx)

    def post(self, request, pk) :
        house = get_object_or_404(self.model, pk=pk)
        house.delete()
        return redirect(self.success_url)
# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class WizardCreate(LoginRequiredMixin,CreateView):
    model = Wizard
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')

class WizardUpdate(LoginRequiredMixin, UpdateView):
    model = Wizard
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')

class WizardDelete(LoginRequiredMixin, DeleteView):
    model = Wizard
    fields = '__all__'
    success_url = reverse_lazy('wizards:all')

wizards/templates/wizards/house_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete House</h1>

<p>Are you sure you want to delete the house: {{ house }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'wizards:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

wizards/templates/wizards/house_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'wizards:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

wizards/templates/wizards/house_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>House List</h1>
  {% if house_list %}
  <ul>
    {% for house in house_list %}
      <li>
          {{ house.name }}
         (<a href="{% url 'wizards:house_update' house.id %}">Update</a> |
          <a href="{% url 'wizards:house_delete' house.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no houses in the library.</p>
  {% endif %}
  <p><a href="{% url 'wizards:house_create' %}">Add a house</a></p>
  <p>
    <a href="{% url 'wizards:all' %}">Back to wizards</a>
  </p>
{% endblock %}

wizards/templates/wizards/wizard_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Wizard</h1>

<p>Are you sure you want to delete the wizard: {{ wizard }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

wizards/templates/wizards/wizard_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'wizards:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

wizards/templates/wizards/wizard_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Wizards List</h1>
  {% if wizard_list %}
  <ul>
    {% for wizard in wizard_list %}
      <li>
          {{ wizard.nickname }} ({{ wizard.type }})
          (<a href="{% url 'wizards:wizard_update' wizard.id %}">Update</a> |
          <a href="{% url 'wizards:wizard_delete' wizard.id %}">Delete</a>) <br/>
          {{ wizard.comments }} ({{ wizard.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no wizards in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'wizards:wizard_create' %}">Add a wizard</a>
    {% else %}
      Please add a type before you add a wizard.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'wizards:house_list' %}">View houses</a> ({{ make_count }}) |
    <a href="{% url 'wizards:house_create' %}">Add a house</a>
  </p>
{% endblock %}