ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    # path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads')), name='ad_comment_delete'),
    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),
    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

horses/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name='horses'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.HorseCreate.as_view(), name='horse_create'),
    path('main/<int:pk>/update/', views.HorseUpdate.as_view(), name='horse_update'),
    path('main/<int:pk>/delete/', views.HorseDelete.as_view(), name='horse_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve


urlpatterns = [
    path('', include('ads.urls')),  # Change to ads.urls
    # path('ads/', include('ads.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
           'show_indexes': True},
        name='site_path'
    ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
        path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
    )
    print('Using',social_login,'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

horses/models.py
from django.db import models

# Create your models here.

from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Horse(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    height = models.PositiveIntegerField()
    weight = models.PositiveIntegerField()
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

horses/forms.py
from django.forms import ModelForm
from horses.models import Breed

# Create the form class.
class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'

horses/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from horses.models import Horse, Breed
from horses.forms import BreedForm

# Create your views here.

class MainView(LoginRequiredMixin, View) :
    def get(self, request):
        mc = Breed.objects.all().count();
        al = Horse.objects.all();

        ctx = { 'make_count': mc, 'horse_list': al };
        return render(request, 'horses/horse_list.html', ctx)

class BreedView(LoginRequiredMixin,View) :
    def get(self, request):
        ml = Breed.objects.all();
        ctx = { 'breed_list': ml };
        return render(request, 'horses/breed_list.html', ctx)

# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class BreedCreate(LoginRequiredMixin, View):
    template = 'horses/breed_form.html'
    success_url = reverse_lazy('horses:all')
    def get(self, request) :
        form = BreedForm()
        ctx = { 'form': form }
        return render(request, self.template, ctx)

    def post(self, request) :
        form = BreedForm(request.POST)
        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        breed = form.save()
        return redirect(self.success_url)

# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class BreedUpdate(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('horses:all')
    template = 'horses/breed_form.html'
    def get(self, request, pk) :
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        ctx = { 'form': form }
        return render(request, self.template, ctx)

    def post(self, request, pk) :
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(request.POST, instance = breed)
        if not form.is_valid() :
            ctx = {'form' : form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)

class BreedDelete(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('horses:all')
    template = 'horses/breed_confirm_delete.html'

    def get(self, request, pk) :
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        ctx = { 'breed': breed }
        return render(request, self.template, ctx)

    def post(self, request, pk) :
        breed = get_object_or_404(self.model, pk=pk)
        breed.delete()
        return redirect(self.success_url)

# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class HorseCreate(LoginRequiredMixin,CreateView):
    model = Horse
    fields = '__all__'
    success_url = reverse_lazy('horses:all')

class HorseUpdate(LoginRequiredMixin, UpdateView):
    model = Horse
    fields = '__all__'
    success_url = reverse_lazy('horses:all')

class HorseDelete(LoginRequiredMixin, DeleteView):
    model = Horse
    fields = '__all__'
    success_url = reverse_lazy('horses:all')

horses/templates/horses/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the breed: {{ breed }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'horses:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

horses/templates/horses/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'horses:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

horses/templates/horses/breed_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Breed List</h1>
  {% if breed_list %}
  <ul>
    {% for breed in breed_list %}
      <li>
          {{ breed.name }}
         (<a href="{% url 'horses:breed_update' breed.id %}">Update</a> |
          <a href="{% url 'horses:breed_delete' breed.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no breeds in the library.</p>
  {% endif %}
  <p><a href="{% url 'horses:breed_create' %}">Add a breed</a></p>
  <p>
    <a href="{% url 'horses:all' %}">Back to horses</a>
  </p>
{% endblock %}

horses/templates/horses/horse_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Horse</h1>

<p>Are you sure you want to delete the horse: {{ horse }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

horses/templates/horses/horse_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'horses:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

horses/templates/horses/horse_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Horses List</h1>
  {% if horse_list %}
  <ul>
    {% for horse in horse_list %}
      <li>
          {{ horse.nickname }} ({{ horse.breed }})
          (<a href="{% url 'horses:horse_update' horse.id %}">Update</a> |
          <a href="{% url 'horses:horse_delete' horse.id %}">Delete</a>) <br/>
          {{ horse.comments }} ({{ horse.mileage }} miles)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no horses in the library.</p>
  {% endif %}
  <p>
    {% if make_count > 0 %}
      <a href="{% url 'horses:horse_create' %}">Add a horse</a>
    {% else %}
      Please add a breed before you add a horse.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'horses:breed_list' %}">View breeds</a> ({{ make_count }}) |
    <a href="{% url 'horses:breed_create' %}">Add a breed</a>
  </p>
{% endblock %}